### ISSUE TITLE
[ERROR] : Joint 'gripper_joint' not found in model 'cyton_gamma_1500'

### ISSUE THREAD

**Issue by Gabriellavoura** [SteveMacenski/cyton_gamma_300-1500_operation_and_simulation#9]
I'm having this problem running, ROS Melodic on ubuntu 18.04, I can move through standup.sh but I can not use rviz because the model does not load due to the reported error.

**Comment by SteveMacenski** [comment]
Hi,
This project was developed largely in ROS Indigo a few years back. I'm not sure if something has changed on the MoveIt! side in the last 2 ROS releases, but that would not surprise me. 

With that said that error does sound vaguely familiar to me from back then, but my goals were around visual servoing not grasping -- I might check that everything is configured to your liking but I'm not sure why the gripper_joint not being found would generally effect the use of this project in rviz, only that the gripper may not be movable in that particular kinematic chain. I think the gripper is its own chain.

**Comment by Gabriellavoura** [comment]
Hi, Thanks for your answer.

 I'm working with the cyton gamma 1500 for assistive robotics, to aid physiotherapy with patients who suffered stroke, I'm not gonna use the grasping features. Just copy the motion using a kinect sensor, but with this error I can't use RVIZ because every time this error occurs the cursor disappear, so I can't plan the trajectory of the robotic manipulator.

I'll keep trying to upgrade to the Melodic distro. Thank you.

**Comment by SteveMacenski** [comment]
> I can't use RVIZ because every time this error occurs the cursor disappear

I'm not exactly sure what you mean by that - but that sounds like an issue with rviz or your machine over this package if the gripper isn't an issue.

**Comment by Gabriellavoura** [comment]
I fixed, the joins must have the same name in the joint_name.yaml file as controllers.yaml

`path: ~/cyton_gamma_1500/gamma_1500_moveit_config/config`

In **_controllers.yaml_**

``` shell
controller_list:
    joints:
      - shoulder_roll_joint
      - shoulder_pitch_joint
      - shoulder_yaw_joint
      - elbow_pitch_joint
      - elbow_yaw_joint
      - wrist_pitch_joint
      - wrist_roll_joint
      - gripper_joint
```

in **_joint_names.yaml:_**

``` shell
controller_joint_names: 
[ shoulder_roll_joint, 
shoulder_pitch_joint, 
shoulder_yaw_joint, 
elbow_pitch_joint, 
elbow_yaw_joint, 
wrist_pitch_joint, 
wrist_roll_joint, 
gripper_joint]
```
